// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9rc9x43IyFL6vFt6QfhPhYqM1qjoyzA',
    appId: '1:1055171283511:web:a9f488fd01183377064db2',
    messagingSenderId: '1055171283511',
    projectId: 'glamore-ecommerce-store',
    authDomain: 'glamore-ecommerce-store.firebaseapp.com',
    storageBucket: 'glamore-ecommerce-store.firebasestorage.app',
    measurementId: 'G-X70XV00SYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Kc93bu7uWDOEqNjGxa6qY-MHSQdOPhQ',
    appId: '1:1055171283511:android:c3f1d79614b8c402064db2',
    messagingSenderId: '1055171283511',
    projectId: 'glamore-ecommerce-store',
    storageBucket: 'glamore-ecommerce-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VQD_J6f-VwdBVqK5aRWkc2VomHibLPw',
    appId: '1:1055171283511:ios:320062c20a34e465064db2',
    messagingSenderId: '1055171283511',
    projectId: 'glamore-ecommerce-store',
    storageBucket: 'glamore-ecommerce-store.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-VQD_J6f-VwdBVqK5aRWkc2VomHibLPw',
    appId: '1:1055171283511:ios:320062c20a34e465064db2',
    messagingSenderId: '1055171283511',
    projectId: 'glamore-ecommerce-store',
    storageBucket: 'glamore-ecommerce-store.firebasestorage.app',
    iosBundleId: 'com.example.ecomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9rc9x43IyFL6vFt6QfhPhYqM1qjoyzA',
    appId: '1:1055171283511:web:74ef229c2fc51415064db2',
    messagingSenderId: '1055171283511',
    projectId: 'glamore-ecommerce-store',
    authDomain: 'glamore-ecommerce-store.firebaseapp.com',
    storageBucket: 'glamore-ecommerce-store.firebasestorage.app',
    measurementId: 'G-HKWSF7D70H',
  );
}
